/**
 * 
 */
package org.openmrs.module.mdrtb.specimen;


public class DstImpl2 {

/*
TUBERCULOSIS SAMPLE SOURCE
TUBERCULOSIS SPECIMEN COMMENTS
TUBERCULOSIS CULTURE RESULT
TUBERCULOSIS CULTURE CONSTRUCT
APPEARANCE OF SPECIMEN
TUBERCULOSIS XPERT TEST CONSTRUCT
MTB RESULT
RIFAMPICIN RESISTANCE
ISONIAZID RESISTANCE
TUBERCULOSIS HAIN TEST CONSTRUCT
MICROSCOPY RESULT
MICROSCOPY TEST CONSTRUCT
HAIN 2 TEST CONSTRUCT
TUBERCULOSIS TEST RESULT DATE
SPUTUM COLLECTION DATE
DATE OF RESULT
DATE OF INOCULATION OF CULTURE
DATE OF REPORTING CULTURE RESULT
DATE OF MGIT GROWTH OCCURRENCE
DATE OF L-J GROWTH OCCURRENCE
DATE OF REPEATED DECONTAMINATION AND 2ND INOCULATION
DATE OF GROWTH OCCURRENCE (2ND DECONT.)
DATE OF READING 1ST-LINE DST RESULTS ON MGIT
DATE 1ST-LINE DST INOCULATION ON MGIT
DATE OF REPORTING 1ST-LINE DST RESULT
DATE OF 1ST-LINE DST INOCULATION ON L-J
DATE OF READING 1ST-LINE DST RESULTS ON L-J
DATE OF 2ND-LINE DST INOCULATION
DATE OF READING 2ND-LINE DST RESULTS
DATE OF REPORTING 2ND-LINE DST RESULT
DATE OF REQUEST FOR LABORATORY INVESTIGATION
DATE OF SENDING TO CULTURE
DATE OF SENDING TO DST
INVESTIGATION DATE
PERIPHERAL LABORATORY INVESTIGATION NUMBER
PURPOSE OF INVESTIGATION
REQUESTING MEDICAL FACILITY
LABORATORY INVESTIGATION NUMBER 
REFERRED BY
REFERRING FACILITY
LABORATORY NO
MT ID TEST
MGIT CULTURE RESULT
TYPE OF CULTURE REPORTED
MGIT RESULT TEMPLATE
PLACE OF CULTURE
L-J CULTURE RESULT
L-J RESULT TEMPLATE
CULTURE RESULT (2ND DECONTAMINATION)
CONTAMINATED TUBES RESULT TEMPLATE
DST1 MGIT CONSTRUCT
STREPTOMYCIN
PYRAZINAMIDE
DST1 CONSTRUCT
TYPE OF DST METHOD REPORTED
DST1 LJ CONSTRUCT
DST2 CONSTRUCT
DST2 MGIT CONSTRUCT
DST2 LJ CONSTRUCT
DST1 LAB LOCATION
DST2 LAB LOCATION
PERIPHERAL LAB BIOLOGICAL SPECIMEN
SENT TO DST
SENT TO CULTURE
LAB SPECIALIST NAME
	AMIKACIN RESISTANCE
	BEDAQUILINE RESISTANCE
	CAPREOMYCIN RESISTANCE
	CIPROFLOXACIN RESISTANCE
	CLARITHROMYCIN RESISTANCE
	CLOFAZAMINE RESISTANCE
	CYCLOSERINE RESISTANCE
	DELAMANID RESISTANCE
	ETHAMBUTOL RESISTANCE
	ETHIONAMIDE RESISTANCE
	GATIFLOXACIN RESISTANCE
	ISONIAZID RESISTANCE
	KANAMYCIN RESISTANCE
	LEVOFLOXACIN RESISTANCE
	LINEZOLID RESISTANCE
	MOXIFLOXACIN RESISTANCE
	OFLOXACIN RESISTANCE
	OTHER RESISTANCE
	P-AMINOSALICY RESISTANCE
	PROTHIONAMIDE RESISTANCE
	PYRAZINAMIDE RESISTANCE
	PYRIDOXINE RESISTANCE
	RIFABUTIN RESISTANCE
	RIFAMPICIN RESISTANCE
	STREPTOMYCIN RESISTANCE
	TERIZIDONE RESISTANCE
	THIOACETAZONE RESISTANCE
	VIOMYCIN RESISTANCE
*/

}
