package org.openmrs.module.mdrtb.lab;

public enum LabTestGroup {
	SEROLOGY, CARDIOLOGY, OPHTHALMOLOGY, BACTERIOLOGY, BIOCHEMISTRY, BLOOD_BANK, CYTOLOGY, HEMATOLOGY, IMMUNOLOGY, MICROBIOLOGY, RADIOLOGY, SONOLOGY, URINALYSIS, OTHER
}
